# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from arbiter.v1 import service_pb2 as arbiter_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in arbiter/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArbiterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishBundle = channel.unary_unary(
                '/arbiter.v1.ArbiterService/PublishBundle',
                request_serializer=arbiter_dot_v1_dot_service__pb2.PublishBundleRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.PublishBundleResponse.FromString,
                _registered_method=True)
        self.ListBundles = channel.unary_unary(
                '/arbiter.v1.ArbiterService/ListBundles',
                request_serializer=arbiter_dot_v1_dot_service__pb2.ListBundlesRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.ListBundlesResponse.FromString,
                _registered_method=True)
        self.ActivateBundle = channel.unary_unary(
                '/arbiter.v1.ArbiterService/ActivateBundle',
                request_serializer=arbiter_dot_v1_dot_service__pb2.ActivateBundleRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.ActivateBundleResponse.FromString,
                _registered_method=True)
        self.RollbackBundle = channel.unary_unary(
                '/arbiter.v1.ArbiterService/RollbackBundle',
                request_serializer=arbiter_dot_v1_dot_service__pb2.RollbackBundleRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.RollbackBundleResponse.FromString,
                _registered_method=True)
        self.GetBundle = channel.unary_unary(
                '/arbiter.v1.ArbiterService/GetBundle',
                request_serializer=arbiter_dot_v1_dot_service__pb2.GetBundleRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.GetBundleResponse.FromString,
                _registered_method=True)
        self.WatchBundles = channel.unary_stream(
                '/arbiter.v1.ArbiterService/WatchBundles',
                request_serializer=arbiter_dot_v1_dot_service__pb2.WatchBundlesRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.BundleEvent.FromString,
                _registered_method=True)
        self.GetOverrides = channel.unary_unary(
                '/arbiter.v1.ArbiterService/GetOverrides',
                request_serializer=arbiter_dot_v1_dot_service__pb2.GetOverridesRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.GetOverridesResponse.FromString,
                _registered_method=True)
        self.WatchOverrides = channel.unary_stream(
                '/arbiter.v1.ArbiterService/WatchOverrides',
                request_serializer=arbiter_dot_v1_dot_service__pb2.WatchOverridesRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.OverrideEvent.FromString,
                _registered_method=True)
        self.EvaluateRules = channel.unary_unary(
                '/arbiter.v1.ArbiterService/EvaluateRules',
                request_serializer=arbiter_dot_v1_dot_service__pb2.EvaluateRulesRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.EvaluateRulesResponse.FromString,
                _registered_method=True)
        self.ResolveFlag = channel.unary_unary(
                '/arbiter.v1.ArbiterService/ResolveFlag',
                request_serializer=arbiter_dot_v1_dot_service__pb2.ResolveFlagRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.ResolveFlagResponse.FromString,
                _registered_method=True)
        self.StartSession = channel.unary_unary(
                '/arbiter.v1.ArbiterService/StartSession',
                request_serializer=arbiter_dot_v1_dot_service__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.RunSession = channel.unary_unary(
                '/arbiter.v1.ArbiterService/RunSession',
                request_serializer=arbiter_dot_v1_dot_service__pb2.RunSessionRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.RunSessionResponse.FromString,
                _registered_method=True)
        self.AssertFacts = channel.unary_unary(
                '/arbiter.v1.ArbiterService/AssertFacts',
                request_serializer=arbiter_dot_v1_dot_service__pb2.AssertFactsRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.AssertFactsResponse.FromString,
                _registered_method=True)
        self.RetractFacts = channel.unary_unary(
                '/arbiter.v1.ArbiterService/RetractFacts',
                request_serializer=arbiter_dot_v1_dot_service__pb2.RetractFactsRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.RetractFactsResponse.FromString,
                _registered_method=True)
        self.GetSessionTrace = channel.unary_unary(
                '/arbiter.v1.ArbiterService/GetSessionTrace',
                request_serializer=arbiter_dot_v1_dot_service__pb2.GetSessionTraceRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.GetSessionTraceResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/arbiter.v1.ArbiterService/CloseSession',
                request_serializer=arbiter_dot_v1_dot_service__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.CloseSessionResponse.FromString,
                _registered_method=True)
        self.SetRuleOverride = channel.unary_unary(
                '/arbiter.v1.ArbiterService/SetRuleOverride',
                request_serializer=arbiter_dot_v1_dot_service__pb2.SetRuleOverrideRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.SetRuleOverrideResponse.FromString,
                _registered_method=True)
        self.SetFlagOverride = channel.unary_unary(
                '/arbiter.v1.ArbiterService/SetFlagOverride',
                request_serializer=arbiter_dot_v1_dot_service__pb2.SetFlagOverrideRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.SetFlagOverrideResponse.FromString,
                _registered_method=True)
        self.SetFlagRuleOverride = channel.unary_unary(
                '/arbiter.v1.ArbiterService/SetFlagRuleOverride',
                request_serializer=arbiter_dot_v1_dot_service__pb2.SetFlagRuleOverrideRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_service__pb2.SetFlagRuleOverrideResponse.FromString,
                _registered_method=True)


class ArbiterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PublishBundle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBundles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateBundle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackBundle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBundle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchBundles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOverrides(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchOverrides(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveFlag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssertFacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetractFacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionTrace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRuleOverride(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFlagOverride(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFlagRuleOverride(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArbiterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishBundle,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.PublishBundleRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.PublishBundleResponse.SerializeToString,
            ),
            'ListBundles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBundles,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.ListBundlesRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.ListBundlesResponse.SerializeToString,
            ),
            'ActivateBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateBundle,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.ActivateBundleRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.ActivateBundleResponse.SerializeToString,
            ),
            'RollbackBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackBundle,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.RollbackBundleRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.RollbackBundleResponse.SerializeToString,
            ),
            'GetBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBundle,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.GetBundleRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.GetBundleResponse.SerializeToString,
            ),
            'WatchBundles': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchBundles,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.WatchBundlesRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.BundleEvent.SerializeToString,
            ),
            'GetOverrides': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverrides,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.GetOverridesRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.GetOverridesResponse.SerializeToString,
            ),
            'WatchOverrides': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchOverrides,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.WatchOverridesRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.OverrideEvent.SerializeToString,
            ),
            'EvaluateRules': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateRules,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.EvaluateRulesRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.EvaluateRulesResponse.SerializeToString,
            ),
            'ResolveFlag': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveFlag,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.ResolveFlagRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.ResolveFlagResponse.SerializeToString,
            ),
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.StartSessionRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.StartSessionResponse.SerializeToString,
            ),
            'RunSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSession,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.RunSessionRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.RunSessionResponse.SerializeToString,
            ),
            'AssertFacts': grpc.unary_unary_rpc_method_handler(
                    servicer.AssertFacts,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.AssertFactsRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.AssertFactsResponse.SerializeToString,
            ),
            'RetractFacts': grpc.unary_unary_rpc_method_handler(
                    servicer.RetractFacts,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.RetractFactsRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.RetractFactsResponse.SerializeToString,
            ),
            'GetSessionTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionTrace,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.GetSessionTraceRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.GetSessionTraceResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.CloseSessionRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.CloseSessionResponse.SerializeToString,
            ),
            'SetRuleOverride': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRuleOverride,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.SetRuleOverrideRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.SetRuleOverrideResponse.SerializeToString,
            ),
            'SetFlagOverride': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFlagOverride,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.SetFlagOverrideRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.SetFlagOverrideResponse.SerializeToString,
            ),
            'SetFlagRuleOverride': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFlagRuleOverride,
                    request_deserializer=arbiter_dot_v1_dot_service__pb2.SetFlagRuleOverrideRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_service__pb2.SetFlagRuleOverrideResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arbiter.v1.ArbiterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arbiter.v1.ArbiterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArbiterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PublishBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/PublishBundle',
            arbiter_dot_v1_dot_service__pb2.PublishBundleRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.PublishBundleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBundles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/ListBundles',
            arbiter_dot_v1_dot_service__pb2.ListBundlesRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.ListBundlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/ActivateBundle',
            arbiter_dot_v1_dot_service__pb2.ActivateBundleRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.ActivateBundleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/RollbackBundle',
            arbiter_dot_v1_dot_service__pb2.RollbackBundleRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.RollbackBundleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/GetBundle',
            arbiter_dot_v1_dot_service__pb2.GetBundleRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.GetBundleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchBundles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arbiter.v1.ArbiterService/WatchBundles',
            arbiter_dot_v1_dot_service__pb2.WatchBundlesRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.BundleEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOverrides(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/GetOverrides',
            arbiter_dot_v1_dot_service__pb2.GetOverridesRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.GetOverridesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchOverrides(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arbiter.v1.ArbiterService/WatchOverrides',
            arbiter_dot_v1_dot_service__pb2.WatchOverridesRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.OverrideEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/EvaluateRules',
            arbiter_dot_v1_dot_service__pb2.EvaluateRulesRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.EvaluateRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveFlag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/ResolveFlag',
            arbiter_dot_v1_dot_service__pb2.ResolveFlagRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.ResolveFlagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/StartSession',
            arbiter_dot_v1_dot_service__pb2.StartSessionRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/RunSession',
            arbiter_dot_v1_dot_service__pb2.RunSessionRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.RunSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssertFacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/AssertFacts',
            arbiter_dot_v1_dot_service__pb2.AssertFactsRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.AssertFactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetractFacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/RetractFacts',
            arbiter_dot_v1_dot_service__pb2.RetractFactsRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.RetractFactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/GetSessionTrace',
            arbiter_dot_v1_dot_service__pb2.GetSessionTraceRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.GetSessionTraceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/CloseSession',
            arbiter_dot_v1_dot_service__pb2.CloseSessionRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRuleOverride(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/SetRuleOverride',
            arbiter_dot_v1_dot_service__pb2.SetRuleOverrideRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.SetRuleOverrideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFlagOverride(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/SetFlagOverride',
            arbiter_dot_v1_dot_service__pb2.SetFlagOverrideRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.SetFlagOverrideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFlagRuleOverride(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.ArbiterService/SetFlagRuleOverride',
            arbiter_dot_v1_dot_service__pb2.SetFlagRuleOverrideRequest.SerializeToString,
            arbiter_dot_v1_dot_service__pb2.SetFlagRuleOverrideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
