// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: arbiter/v1/service.proto

package arbiterv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArbiterService_PublishBundle_FullMethodName       = "/arbiter.v1.ArbiterService/PublishBundle"
	ArbiterService_EvaluateRules_FullMethodName       = "/arbiter.v1.ArbiterService/EvaluateRules"
	ArbiterService_ResolveFlag_FullMethodName         = "/arbiter.v1.ArbiterService/ResolveFlag"
	ArbiterService_StartSession_FullMethodName        = "/arbiter.v1.ArbiterService/StartSession"
	ArbiterService_RunSession_FullMethodName          = "/arbiter.v1.ArbiterService/RunSession"
	ArbiterService_AssertFacts_FullMethodName         = "/arbiter.v1.ArbiterService/AssertFacts"
	ArbiterService_RetractFacts_FullMethodName        = "/arbiter.v1.ArbiterService/RetractFacts"
	ArbiterService_GetSessionTrace_FullMethodName     = "/arbiter.v1.ArbiterService/GetSessionTrace"
	ArbiterService_SetRuleOverride_FullMethodName     = "/arbiter.v1.ArbiterService/SetRuleOverride"
	ArbiterService_SetFlagOverride_FullMethodName     = "/arbiter.v1.ArbiterService/SetFlagOverride"
	ArbiterService_SetFlagRuleOverride_FullMethodName = "/arbiter.v1.ArbiterService/SetFlagRuleOverride"
)

// ArbiterServiceClient is the client API for ArbiterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArbiterServiceClient interface {
	PublishBundle(ctx context.Context, in *PublishBundleRequest, opts ...grpc.CallOption) (*PublishBundleResponse, error)
	EvaluateRules(ctx context.Context, in *EvaluateRulesRequest, opts ...grpc.CallOption) (*EvaluateRulesResponse, error)
	ResolveFlag(ctx context.Context, in *ResolveFlagRequest, opts ...grpc.CallOption) (*ResolveFlagResponse, error)
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	RunSession(ctx context.Context, in *RunSessionRequest, opts ...grpc.CallOption) (*RunSessionResponse, error)
	AssertFacts(ctx context.Context, in *AssertFactsRequest, opts ...grpc.CallOption) (*AssertFactsResponse, error)
	RetractFacts(ctx context.Context, in *RetractFactsRequest, opts ...grpc.CallOption) (*RetractFactsResponse, error)
	GetSessionTrace(ctx context.Context, in *GetSessionTraceRequest, opts ...grpc.CallOption) (*GetSessionTraceResponse, error)
	SetRuleOverride(ctx context.Context, in *SetRuleOverrideRequest, opts ...grpc.CallOption) (*SetRuleOverrideResponse, error)
	SetFlagOverride(ctx context.Context, in *SetFlagOverrideRequest, opts ...grpc.CallOption) (*SetFlagOverrideResponse, error)
	SetFlagRuleOverride(ctx context.Context, in *SetFlagRuleOverrideRequest, opts ...grpc.CallOption) (*SetFlagRuleOverrideResponse, error)
}

type arbiterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArbiterServiceClient(cc grpc.ClientConnInterface) ArbiterServiceClient {
	return &arbiterServiceClient{cc}
}

func (c *arbiterServiceClient) PublishBundle(ctx context.Context, in *PublishBundleRequest, opts ...grpc.CallOption) (*PublishBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishBundleResponse)
	err := c.cc.Invoke(ctx, ArbiterService_PublishBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arbiterServiceClient) EvaluateRules(ctx context.Context, in *EvaluateRulesRequest, opts ...grpc.CallOption) (*EvaluateRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateRulesResponse)
	err := c.cc.Invoke(ctx, ArbiterService_EvaluateRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arbiterServiceClient) ResolveFlag(ctx context.Context, in *ResolveFlagRequest, opts ...grpc.CallOption) (*ResolveFlagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveFlagResponse)
	err := c.cc.Invoke(ctx, ArbiterService_ResolveFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arbiterServiceClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, ArbiterService_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arbiterServiceClient) RunSession(ctx context.Context, in *RunSessionRequest, opts ...grpc.CallOption) (*RunSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunSessionResponse)
	err := c.cc.Invoke(ctx, ArbiterService_RunSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arbiterServiceClient) AssertFacts(ctx context.Context, in *AssertFactsRequest, opts ...grpc.CallOption) (*AssertFactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssertFactsResponse)
	err := c.cc.Invoke(ctx, ArbiterService_AssertFacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arbiterServiceClient) RetractFacts(ctx context.Context, in *RetractFactsRequest, opts ...grpc.CallOption) (*RetractFactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetractFactsResponse)
	err := c.cc.Invoke(ctx, ArbiterService_RetractFacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arbiterServiceClient) GetSessionTrace(ctx context.Context, in *GetSessionTraceRequest, opts ...grpc.CallOption) (*GetSessionTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionTraceResponse)
	err := c.cc.Invoke(ctx, ArbiterService_GetSessionTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arbiterServiceClient) SetRuleOverride(ctx context.Context, in *SetRuleOverrideRequest, opts ...grpc.CallOption) (*SetRuleOverrideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRuleOverrideResponse)
	err := c.cc.Invoke(ctx, ArbiterService_SetRuleOverride_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arbiterServiceClient) SetFlagOverride(ctx context.Context, in *SetFlagOverrideRequest, opts ...grpc.CallOption) (*SetFlagOverrideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFlagOverrideResponse)
	err := c.cc.Invoke(ctx, ArbiterService_SetFlagOverride_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arbiterServiceClient) SetFlagRuleOverride(ctx context.Context, in *SetFlagRuleOverrideRequest, opts ...grpc.CallOption) (*SetFlagRuleOverrideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFlagRuleOverrideResponse)
	err := c.cc.Invoke(ctx, ArbiterService_SetFlagRuleOverride_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArbiterServiceServer is the server API for ArbiterService service.
// All implementations must embed UnimplementedArbiterServiceServer
// for forward compatibility.
type ArbiterServiceServer interface {
	PublishBundle(context.Context, *PublishBundleRequest) (*PublishBundleResponse, error)
	EvaluateRules(context.Context, *EvaluateRulesRequest) (*EvaluateRulesResponse, error)
	ResolveFlag(context.Context, *ResolveFlagRequest) (*ResolveFlagResponse, error)
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	RunSession(context.Context, *RunSessionRequest) (*RunSessionResponse, error)
	AssertFacts(context.Context, *AssertFactsRequest) (*AssertFactsResponse, error)
	RetractFacts(context.Context, *RetractFactsRequest) (*RetractFactsResponse, error)
	GetSessionTrace(context.Context, *GetSessionTraceRequest) (*GetSessionTraceResponse, error)
	SetRuleOverride(context.Context, *SetRuleOverrideRequest) (*SetRuleOverrideResponse, error)
	SetFlagOverride(context.Context, *SetFlagOverrideRequest) (*SetFlagOverrideResponse, error)
	SetFlagRuleOverride(context.Context, *SetFlagRuleOverrideRequest) (*SetFlagRuleOverrideResponse, error)
	mustEmbedUnimplementedArbiterServiceServer()
}

// UnimplementedArbiterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArbiterServiceServer struct{}

func (UnimplementedArbiterServiceServer) PublishBundle(context.Context, *PublishBundleRequest) (*PublishBundleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishBundle not implemented")
}
func (UnimplementedArbiterServiceServer) EvaluateRules(context.Context, *EvaluateRulesRequest) (*EvaluateRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateRules not implemented")
}
func (UnimplementedArbiterServiceServer) ResolveFlag(context.Context, *ResolveFlagRequest) (*ResolveFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveFlag not implemented")
}
func (UnimplementedArbiterServiceServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedArbiterServiceServer) RunSession(context.Context, *RunSessionRequest) (*RunSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSession not implemented")
}
func (UnimplementedArbiterServiceServer) AssertFacts(context.Context, *AssertFactsRequest) (*AssertFactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssertFacts not implemented")
}
func (UnimplementedArbiterServiceServer) RetractFacts(context.Context, *RetractFactsRequest) (*RetractFactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetractFacts not implemented")
}
func (UnimplementedArbiterServiceServer) GetSessionTrace(context.Context, *GetSessionTraceRequest) (*GetSessionTraceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionTrace not implemented")
}
func (UnimplementedArbiterServiceServer) SetRuleOverride(context.Context, *SetRuleOverrideRequest) (*SetRuleOverrideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRuleOverride not implemented")
}
func (UnimplementedArbiterServiceServer) SetFlagOverride(context.Context, *SetFlagOverrideRequest) (*SetFlagOverrideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFlagOverride not implemented")
}
func (UnimplementedArbiterServiceServer) SetFlagRuleOverride(context.Context, *SetFlagRuleOverrideRequest) (*SetFlagRuleOverrideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFlagRuleOverride not implemented")
}
func (UnimplementedArbiterServiceServer) mustEmbedUnimplementedArbiterServiceServer() {}
func (UnimplementedArbiterServiceServer) testEmbeddedByValue()                        {}

// UnsafeArbiterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArbiterServiceServer will
// result in compilation errors.
type UnsafeArbiterServiceServer interface {
	mustEmbedUnimplementedArbiterServiceServer()
}

func RegisterArbiterServiceServer(s grpc.ServiceRegistrar, srv ArbiterServiceServer) {
	// If the following call pancis, it indicates UnimplementedArbiterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArbiterService_ServiceDesc, srv)
}

func _ArbiterService_PublishBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArbiterServiceServer).PublishBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArbiterService_PublishBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArbiterServiceServer).PublishBundle(ctx, req.(*PublishBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArbiterService_EvaluateRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArbiterServiceServer).EvaluateRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArbiterService_EvaluateRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArbiterServiceServer).EvaluateRules(ctx, req.(*EvaluateRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArbiterService_ResolveFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArbiterServiceServer).ResolveFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArbiterService_ResolveFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArbiterServiceServer).ResolveFlag(ctx, req.(*ResolveFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArbiterService_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArbiterServiceServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArbiterService_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArbiterServiceServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArbiterService_RunSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArbiterServiceServer).RunSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArbiterService_RunSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArbiterServiceServer).RunSession(ctx, req.(*RunSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArbiterService_AssertFacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssertFactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArbiterServiceServer).AssertFacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArbiterService_AssertFacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArbiterServiceServer).AssertFacts(ctx, req.(*AssertFactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArbiterService_RetractFacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetractFactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArbiterServiceServer).RetractFacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArbiterService_RetractFacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArbiterServiceServer).RetractFacts(ctx, req.(*RetractFactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArbiterService_GetSessionTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArbiterServiceServer).GetSessionTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArbiterService_GetSessionTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArbiterServiceServer).GetSessionTrace(ctx, req.(*GetSessionTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArbiterService_SetRuleOverride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRuleOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArbiterServiceServer).SetRuleOverride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArbiterService_SetRuleOverride_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArbiterServiceServer).SetRuleOverride(ctx, req.(*SetRuleOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArbiterService_SetFlagOverride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFlagOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArbiterServiceServer).SetFlagOverride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArbiterService_SetFlagOverride_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArbiterServiceServer).SetFlagOverride(ctx, req.(*SetFlagOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArbiterService_SetFlagRuleOverride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFlagRuleOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArbiterServiceServer).SetFlagRuleOverride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArbiterService_SetFlagRuleOverride_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArbiterServiceServer).SetFlagRuleOverride(ctx, req.(*SetFlagRuleOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArbiterService_ServiceDesc is the grpc.ServiceDesc for ArbiterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArbiterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arbiter.v1.ArbiterService",
	HandlerType: (*ArbiterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishBundle",
			Handler:    _ArbiterService_PublishBundle_Handler,
		},
		{
			MethodName: "EvaluateRules",
			Handler:    _ArbiterService_EvaluateRules_Handler,
		},
		{
			MethodName: "ResolveFlag",
			Handler:    _ArbiterService_ResolveFlag_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _ArbiterService_StartSession_Handler,
		},
		{
			MethodName: "RunSession",
			Handler:    _ArbiterService_RunSession_Handler,
		},
		{
			MethodName: "AssertFacts",
			Handler:    _ArbiterService_AssertFacts_Handler,
		},
		{
			MethodName: "RetractFacts",
			Handler:    _ArbiterService_RetractFacts_Handler,
		},
		{
			MethodName: "GetSessionTrace",
			Handler:    _ArbiterService_GetSessionTrace_Handler,
		},
		{
			MethodName: "SetRuleOverride",
			Handler:    _ArbiterService_SetRuleOverride_Handler,
		},
		{
			MethodName: "SetFlagOverride",
			Handler:    _ArbiterService_SetFlagOverride_Handler,
		},
		{
			MethodName: "SetFlagRuleOverride",
			Handler:    _ArbiterService_SetFlagRuleOverride_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arbiter/v1/service.proto",
}
