// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: arbiter/v1/service.proto

package arbiterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source        []byte                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBundleRequest) Reset() {
	*x = PublishBundleRequest{}
	mi := &file_arbiter_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBundleRequest) ProtoMessage() {}

func (x *PublishBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBundleRequest.ProtoReflect.Descriptor instead.
func (*PublishBundleRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *PublishBundleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublishBundleRequest) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

type PublishBundleResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BundleId        string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	Checksum        string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	RuleCount       uint32                 `protobuf:"varint,3,opt,name=rule_count,json=ruleCount,proto3" json:"rule_count,omitempty"`
	FlagCount       uint32                 `protobuf:"varint,4,opt,name=flag_count,json=flagCount,proto3" json:"flag_count,omitempty"`
	PublishedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	ExpertRuleCount uint32                 `protobuf:"varint,6,opt,name=expert_rule_count,json=expertRuleCount,proto3" json:"expert_rule_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PublishBundleResponse) Reset() {
	*x = PublishBundleResponse{}
	mi := &file_arbiter_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBundleResponse) ProtoMessage() {}

func (x *PublishBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBundleResponse.ProtoReflect.Descriptor instead.
func (*PublishBundleResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *PublishBundleResponse) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *PublishBundleResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *PublishBundleResponse) GetRuleCount() uint32 {
	if x != nil {
		return x.RuleCount
	}
	return 0
}

func (x *PublishBundleResponse) GetFlagCount() uint32 {
	if x != nil {
		return x.FlagCount
	}
	return 0
}

func (x *PublishBundleResponse) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *PublishBundleResponse) GetExpertRuleCount() uint32 {
	if x != nil {
		return x.ExpertRuleCount
	}
	return 0
}

type TraceStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Check         string                 `protobuf:"bytes,1,opt,name=check,proto3" json:"check,omitempty"`
	Result        bool                   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceStep) Reset() {
	*x = TraceStep{}
	mi := &file_arbiter_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceStep) ProtoMessage() {}

func (x *TraceStep) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceStep.ProtoReflect.Descriptor instead.
func (*TraceStep) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *TraceStep) GetCheck() string {
	if x != nil {
		return x.Check
	}
	return ""
}

func (x *TraceStep) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *TraceStep) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type RuleMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	Fallback      bool                   `protobuf:"varint,5,opt,name=fallback,proto3" json:"fallback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleMatch) Reset() {
	*x = RuleMatch{}
	mi := &file_arbiter_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleMatch) ProtoMessage() {}

func (x *RuleMatch) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleMatch.ProtoReflect.Descriptor instead.
func (*RuleMatch) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *RuleMatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleMatch) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RuleMatch) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RuleMatch) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *RuleMatch) GetFallback() bool {
	if x != nil {
		return x.Fallback
	}
	return false
}

type EvaluateRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleId      string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRulesRequest) Reset() {
	*x = EvaluateRulesRequest{}
	mi := &file_arbiter_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRulesRequest) ProtoMessage() {}

func (x *EvaluateRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRulesRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRulesRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *EvaluateRulesRequest) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *EvaluateRulesRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *EvaluateRulesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type EvaluateRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matched       []*RuleMatch           `protobuf:"bytes,1,rep,name=matched,proto3" json:"matched,omitempty"`
	Trace         []*TraceStep           `protobuf:"bytes,2,rep,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRulesResponse) Reset() {
	*x = EvaluateRulesResponse{}
	mi := &file_arbiter_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRulesResponse) ProtoMessage() {}

func (x *EvaluateRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRulesResponse.ProtoReflect.Descriptor instead.
func (*EvaluateRulesResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *EvaluateRulesResponse) GetMatched() []*RuleMatch {
	if x != nil {
		return x.Matched
	}
	return nil
}

func (x *EvaluateRulesResponse) GetTrace() []*TraceStep {
	if x != nil {
		return x.Trace
	}
	return nil
}

type ResolveFlagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleId      string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	FlagKey       string                 `protobuf:"bytes,2,opt,name=flag_key,json=flagKey,proto3" json:"flag_key,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveFlagRequest) Reset() {
	*x = ResolveFlagRequest{}
	mi := &file_arbiter_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveFlagRequest) ProtoMessage() {}

func (x *ResolveFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveFlagRequest.ProtoReflect.Descriptor instead.
func (*ResolveFlagRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveFlagRequest) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *ResolveFlagRequest) GetFlagKey() string {
	if x != nil {
		return x.FlagKey
	}
	return ""
}

func (x *ResolveFlagRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ResolveFlagRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ResolveFlagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variant       string                 `protobuf:"bytes,1,opt,name=variant,proto3" json:"variant,omitempty"`
	Values        *structpb.Struct       `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	IsDefault     bool                   `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Trace         []*TraceStep           `protobuf:"bytes,5,rep,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveFlagResponse) Reset() {
	*x = ResolveFlagResponse{}
	mi := &file_arbiter_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveFlagResponse) ProtoMessage() {}

func (x *ResolveFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveFlagResponse.ProtoReflect.Descriptor instead.
func (*ResolveFlagResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveFlagResponse) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *ResolveFlagResponse) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ResolveFlagResponse) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *ResolveFlagResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ResolveFlagResponse) GetTrace() []*TraceStep {
	if x != nil {
		return x.Trace
	}
	return nil
}

type ExpertFact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Fields        *structpb.Struct       `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpertFact) Reset() {
	*x = ExpertFact{}
	mi := &file_arbiter_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpertFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpertFact) ProtoMessage() {}

func (x *ExpertFact) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpertFact.ProtoReflect.Descriptor instead.
func (*ExpertFact) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *ExpertFact) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExpertFact) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ExpertFact) GetFields() *structpb.Struct {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ExpertOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          string                 `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpertOutcome) Reset() {
	*x = ExpertOutcome{}
	mi := &file_arbiter_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpertOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpertOutcome) ProtoMessage() {}

func (x *ExpertOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpertOutcome.ProtoReflect.Descriptor instead.
func (*ExpertOutcome) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *ExpertOutcome) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *ExpertOutcome) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExpertOutcome) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

type ExpertActivation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         uint32                 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Rule          string                 `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,5,opt,name=params,proto3" json:"params,omitempty"`
	Changed       bool                   `protobuf:"varint,6,opt,name=changed,proto3" json:"changed,omitempty"`
	Detail        string                 `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpertActivation) Reset() {
	*x = ExpertActivation{}
	mi := &file_arbiter_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpertActivation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpertActivation) ProtoMessage() {}

func (x *ExpertActivation) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpertActivation.ProtoReflect.Descriptor instead.
func (*ExpertActivation) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *ExpertActivation) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ExpertActivation) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *ExpertActivation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ExpertActivation) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ExpertActivation) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExpertActivation) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *ExpertActivation) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleId      string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	Envelope      *structpb.Struct       `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Facts         []*ExpertFact          `protobuf:"bytes,3,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_arbiter_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *StartSessionRequest) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *StartSessionRequest) GetEnvelope() *structpb.Struct {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *StartSessionRequest) GetFacts() []*ExpertFact {
	if x != nil {
		return x.Facts
	}
	return nil
}

type StartSessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExpertRuleCount uint32                 `protobuf:"varint,2,opt,name=expert_rule_count,json=expertRuleCount,proto3" json:"expert_rule_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_arbiter_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *StartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSessionResponse) GetExpertRuleCount() uint32 {
	if x != nil {
		return x.ExpertRuleCount
	}
	return 0
}

type RunSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSessionRequest) Reset() {
	*x = RunSessionRequest{}
	mi := &file_arbiter_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSessionRequest) ProtoMessage() {}

func (x *RunSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSessionRequest.ProtoReflect.Descriptor instead.
func (*RunSessionRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *RunSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunSessionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RunSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcomes      []*ExpertOutcome       `protobuf:"bytes,1,rep,name=outcomes,proto3" json:"outcomes,omitempty"`
	Facts         []*ExpertFact          `protobuf:"bytes,2,rep,name=facts,proto3" json:"facts,omitempty"`
	Activations   []*ExpertActivation    `protobuf:"bytes,3,rep,name=activations,proto3" json:"activations,omitempty"`
	StopReason    string                 `protobuf:"bytes,4,opt,name=stop_reason,json=stopReason,proto3" json:"stop_reason,omitempty"`
	Rounds        uint32                 `protobuf:"varint,5,opt,name=rounds,proto3" json:"rounds,omitempty"`
	Mutations     uint32                 `protobuf:"varint,6,opt,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSessionResponse) Reset() {
	*x = RunSessionResponse{}
	mi := &file_arbiter_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSessionResponse) ProtoMessage() {}

func (x *RunSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSessionResponse.ProtoReflect.Descriptor instead.
func (*RunSessionResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *RunSessionResponse) GetOutcomes() []*ExpertOutcome {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

func (x *RunSessionResponse) GetFacts() []*ExpertFact {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *RunSessionResponse) GetActivations() []*ExpertActivation {
	if x != nil {
		return x.Activations
	}
	return nil
}

func (x *RunSessionResponse) GetStopReason() string {
	if x != nil {
		return x.StopReason
	}
	return ""
}

func (x *RunSessionResponse) GetRounds() uint32 {
	if x != nil {
		return x.Rounds
	}
	return 0
}

func (x *RunSessionResponse) GetMutations() uint32 {
	if x != nil {
		return x.Mutations
	}
	return 0
}

type AssertFactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Facts         []*ExpertFact          `protobuf:"bytes,2,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertFactsRequest) Reset() {
	*x = AssertFactsRequest{}
	mi := &file_arbiter_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertFactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertFactsRequest) ProtoMessage() {}

func (x *AssertFactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertFactsRequest.ProtoReflect.Descriptor instead.
func (*AssertFactsRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *AssertFactsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AssertFactsRequest) GetFacts() []*ExpertFact {
	if x != nil {
		return x.Facts
	}
	return nil
}

type AssertFactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertFactsResponse) Reset() {
	*x = AssertFactsResponse{}
	mi := &file_arbiter_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertFactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertFactsResponse) ProtoMessage() {}

func (x *AssertFactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertFactsResponse.ProtoReflect.Descriptor instead.
func (*AssertFactsResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{16}
}

type FactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactRef) Reset() {
	*x = FactRef{}
	mi := &file_arbiter_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactRef) ProtoMessage() {}

func (x *FactRef) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactRef.ProtoReflect.Descriptor instead.
func (*FactRef) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *FactRef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FactRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RetractFactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Facts         []*FactRef             `protobuf:"bytes,2,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractFactsRequest) Reset() {
	*x = RetractFactsRequest{}
	mi := &file_arbiter_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractFactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractFactsRequest) ProtoMessage() {}

func (x *RetractFactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractFactsRequest.ProtoReflect.Descriptor instead.
func (*RetractFactsRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{18}
}

func (x *RetractFactsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RetractFactsRequest) GetFacts() []*FactRef {
	if x != nil {
		return x.Facts
	}
	return nil
}

type RetractFactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractFactsResponse) Reset() {
	*x = RetractFactsResponse{}
	mi := &file_arbiter_v1_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractFactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractFactsResponse) ProtoMessage() {}

func (x *RetractFactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractFactsResponse.ProtoReflect.Descriptor instead.
func (*RetractFactsResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{19}
}

type GetSessionTraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionTraceRequest) Reset() {
	*x = GetSessionTraceRequest{}
	mi := &file_arbiter_v1_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionTraceRequest) ProtoMessage() {}

func (x *GetSessionTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionTraceRequest.ProtoReflect.Descriptor instead.
func (*GetSessionTraceRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetSessionTraceRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionTraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcomes      []*ExpertOutcome       `protobuf:"bytes,1,rep,name=outcomes,proto3" json:"outcomes,omitempty"`
	Facts         []*ExpertFact          `protobuf:"bytes,2,rep,name=facts,proto3" json:"facts,omitempty"`
	Activations   []*ExpertActivation    `protobuf:"bytes,3,rep,name=activations,proto3" json:"activations,omitempty"`
	StopReason    string                 `protobuf:"bytes,4,opt,name=stop_reason,json=stopReason,proto3" json:"stop_reason,omitempty"`
	Rounds        uint32                 `protobuf:"varint,5,opt,name=rounds,proto3" json:"rounds,omitempty"`
	Mutations     uint32                 `protobuf:"varint,6,opt,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionTraceResponse) Reset() {
	*x = GetSessionTraceResponse{}
	mi := &file_arbiter_v1_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionTraceResponse) ProtoMessage() {}

func (x *GetSessionTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionTraceResponse.ProtoReflect.Descriptor instead.
func (*GetSessionTraceResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetSessionTraceResponse) GetOutcomes() []*ExpertOutcome {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

func (x *GetSessionTraceResponse) GetFacts() []*ExpertFact {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *GetSessionTraceResponse) GetActivations() []*ExpertActivation {
	if x != nil {
		return x.Activations
	}
	return nil
}

func (x *GetSessionTraceResponse) GetStopReason() string {
	if x != nil {
		return x.StopReason
	}
	return ""
}

func (x *GetSessionTraceResponse) GetRounds() uint32 {
	if x != nil {
		return x.Rounds
	}
	return 0
}

func (x *GetSessionTraceResponse) GetMutations() uint32 {
	if x != nil {
		return x.Mutations
	}
	return 0
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_arbiter_v1_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{22}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_arbiter_v1_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{23}
}

type SetRuleOverrideRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BundleId      string                  `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	RuleName      string                  `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	KillSwitch    *wrapperspb.BoolValue   `protobuf:"bytes,3,opt,name=kill_switch,json=killSwitch,proto3" json:"kill_switch,omitempty"`
	Rollout       *wrapperspb.UInt32Value `protobuf:"bytes,4,opt,name=rollout,proto3" json:"rollout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRuleOverrideRequest) Reset() {
	*x = SetRuleOverrideRequest{}
	mi := &file_arbiter_v1_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRuleOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRuleOverrideRequest) ProtoMessage() {}

func (x *SetRuleOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRuleOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetRuleOverrideRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{24}
}

func (x *SetRuleOverrideRequest) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *SetRuleOverrideRequest) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *SetRuleOverrideRequest) GetKillSwitch() *wrapperspb.BoolValue {
	if x != nil {
		return x.KillSwitch
	}
	return nil
}

func (x *SetRuleOverrideRequest) GetRollout() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Rollout
	}
	return nil
}

type SetRuleOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRuleOverrideResponse) Reset() {
	*x = SetRuleOverrideResponse{}
	mi := &file_arbiter_v1_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRuleOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRuleOverrideResponse) ProtoMessage() {}

func (x *SetRuleOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRuleOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetRuleOverrideResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{25}
}

type SetFlagOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleId      string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	FlagKey       string                 `protobuf:"bytes,2,opt,name=flag_key,json=flagKey,proto3" json:"flag_key,omitempty"`
	KillSwitch    *wrapperspb.BoolValue  `protobuf:"bytes,3,opt,name=kill_switch,json=killSwitch,proto3" json:"kill_switch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFlagOverrideRequest) Reset() {
	*x = SetFlagOverrideRequest{}
	mi := &file_arbiter_v1_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFlagOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFlagOverrideRequest) ProtoMessage() {}

func (x *SetFlagOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFlagOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetFlagOverrideRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{26}
}

func (x *SetFlagOverrideRequest) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *SetFlagOverrideRequest) GetFlagKey() string {
	if x != nil {
		return x.FlagKey
	}
	return ""
}

func (x *SetFlagOverrideRequest) GetKillSwitch() *wrapperspb.BoolValue {
	if x != nil {
		return x.KillSwitch
	}
	return nil
}

type SetFlagOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFlagOverrideResponse) Reset() {
	*x = SetFlagOverrideResponse{}
	mi := &file_arbiter_v1_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFlagOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFlagOverrideResponse) ProtoMessage() {}

func (x *SetFlagOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFlagOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetFlagOverrideResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{27}
}

type SetFlagRuleOverrideRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BundleId      string                  `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	FlagKey       string                  `protobuf:"bytes,2,opt,name=flag_key,json=flagKey,proto3" json:"flag_key,omitempty"`
	RuleIndex     uint32                  `protobuf:"varint,3,opt,name=rule_index,json=ruleIndex,proto3" json:"rule_index,omitempty"`
	Rollout       *wrapperspb.UInt32Value `protobuf:"bytes,4,opt,name=rollout,proto3" json:"rollout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFlagRuleOverrideRequest) Reset() {
	*x = SetFlagRuleOverrideRequest{}
	mi := &file_arbiter_v1_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFlagRuleOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFlagRuleOverrideRequest) ProtoMessage() {}

func (x *SetFlagRuleOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFlagRuleOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetFlagRuleOverrideRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{28}
}

func (x *SetFlagRuleOverrideRequest) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *SetFlagRuleOverrideRequest) GetFlagKey() string {
	if x != nil {
		return x.FlagKey
	}
	return ""
}

func (x *SetFlagRuleOverrideRequest) GetRuleIndex() uint32 {
	if x != nil {
		return x.RuleIndex
	}
	return 0
}

func (x *SetFlagRuleOverrideRequest) GetRollout() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Rollout
	}
	return nil
}

type SetFlagRuleOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFlagRuleOverrideResponse) Reset() {
	*x = SetFlagRuleOverrideResponse{}
	mi := &file_arbiter_v1_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFlagRuleOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFlagRuleOverrideResponse) ProtoMessage() {}

func (x *SetFlagRuleOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFlagRuleOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetFlagRuleOverrideResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_service_proto_rawDescGZIP(), []int{29}
}

var File_arbiter_v1_service_proto protoreflect.FileDescriptor

const file_arbiter_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18arbiter/v1/service.proto\x12\n" +
	"arbiter.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"B\n" +
	"\x14PublishBundleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\fR\x06source\"\xf9\x01\n" +
	"\x15PublishBundleResponse\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\x12\x1d\n" +
	"\n" +
	"rule_count\x18\x03 \x01(\rR\truleCount\x12\x1d\n" +
	"\n" +
	"flag_count\x18\x04 \x01(\rR\tflagCount\x12=\n" +
	"\fpublished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12*\n" +
	"\x11expert_rule_count\x18\x06 \x01(\rR\x0fexpertRuleCount\"Q\n" +
	"\tTraceStep\x12\x14\n" +
	"\x05check\x18\x01 \x01(\tR\x05check\x12\x16\n" +
	"\x06result\x18\x02 \x01(\bR\x06result\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\xa0\x01\n" +
	"\tRuleMatch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12/\n" +
	"\x06params\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06params\x12\x1a\n" +
	"\bfallback\x18\x05 \x01(\bR\bfallback\"\x85\x01\n" +
	"\x14EvaluateRulesRequest\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x121\n" +
	"\acontext\x18\x02 \x01(\v2\x17.google.protobuf.StructR\acontext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"u\n" +
	"\x15EvaluateRulesResponse\x12/\n" +
	"\amatched\x18\x01 \x03(\v2\x15.arbiter.v1.RuleMatchR\amatched\x12+\n" +
	"\x05trace\x18\x02 \x03(\v2\x15.arbiter.v1.TraceStepR\x05trace\"\x9e\x01\n" +
	"\x12ResolveFlagRequest\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x12\x19\n" +
	"\bflag_key\x18\x02 \x01(\tR\aflagKey\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.google.protobuf.StructR\acontext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\xc4\x01\n" +
	"\x13ResolveFlagResponse\x12\x18\n" +
	"\avariant\x18\x01 \x01(\tR\avariant\x12/\n" +
	"\x06values\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06values\x12\x1d\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bR\tisDefault\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12+\n" +
	"\x05trace\x18\x05 \x03(\v2\x15.arbiter.v1.TraceStepR\x05trace\"c\n" +
	"\n" +
	"ExpertFact\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12/\n" +
	"\x06fields\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06fields\"h\n" +
	"\rExpertOutcome\x12\x12\n" +
	"\x04rule\x18\x01 \x01(\tR\x04rule\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x06params\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06params\"\xcb\x01\n" +
	"\x10ExpertActivation\x12\x14\n" +
	"\x05round\x18\x01 \x01(\rR\x05round\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12/\n" +
	"\x06params\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06params\x12\x18\n" +
	"\achanged\x18\x06 \x01(\bR\achanged\x12\x16\n" +
	"\x06detail\x18\a \x01(\tR\x06detail\"\x95\x01\n" +
	"\x13StartSessionRequest\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x123\n" +
	"\benvelope\x18\x02 \x01(\v2\x17.google.protobuf.StructR\benvelope\x12,\n" +
	"\x05facts\x18\x03 \x03(\v2\x16.arbiter.v1.ExpertFactR\x05facts\"a\n" +
	"\x14StartSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12*\n" +
	"\x11expert_rule_count\x18\x02 \x01(\rR\x0fexpertRuleCount\"Q\n" +
	"\x11RunSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"\x90\x02\n" +
	"\x12RunSessionResponse\x125\n" +
	"\boutcomes\x18\x01 \x03(\v2\x19.arbiter.v1.ExpertOutcomeR\boutcomes\x12,\n" +
	"\x05facts\x18\x02 \x03(\v2\x16.arbiter.v1.ExpertFactR\x05facts\x12>\n" +
	"\vactivations\x18\x03 \x03(\v2\x1c.arbiter.v1.ExpertActivationR\vactivations\x12\x1f\n" +
	"\vstop_reason\x18\x04 \x01(\tR\n" +
	"stopReason\x12\x16\n" +
	"\x06rounds\x18\x05 \x01(\rR\x06rounds\x12\x1c\n" +
	"\tmutations\x18\x06 \x01(\rR\tmutations\"a\n" +
	"\x12AssertFactsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12,\n" +
	"\x05facts\x18\x02 \x03(\v2\x16.arbiter.v1.ExpertFactR\x05facts\"\x15\n" +
	"\x13AssertFactsResponse\"/\n" +
	"\aFactRef\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"_\n" +
	"\x13RetractFactsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x05facts\x18\x02 \x03(\v2\x13.arbiter.v1.FactRefR\x05facts\"\x16\n" +
	"\x14RetractFactsResponse\"7\n" +
	"\x16GetSessionTraceRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x95\x02\n" +
	"\x17GetSessionTraceResponse\x125\n" +
	"\boutcomes\x18\x01 \x03(\v2\x19.arbiter.v1.ExpertOutcomeR\boutcomes\x12,\n" +
	"\x05facts\x18\x02 \x03(\v2\x16.arbiter.v1.ExpertFactR\x05facts\x12>\n" +
	"\vactivations\x18\x03 \x03(\v2\x1c.arbiter.v1.ExpertActivationR\vactivations\x12\x1f\n" +
	"\vstop_reason\x18\x04 \x01(\tR\n" +
	"stopReason\x12\x16\n" +
	"\x06rounds\x18\x05 \x01(\rR\x06rounds\x12\x1c\n" +
	"\tmutations\x18\x06 \x01(\rR\tmutations\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14CloseSessionResponse\"\xc7\x01\n" +
	"\x16SetRuleOverrideRequest\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12;\n" +
	"\vkill_switch\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\n" +
	"killSwitch\x126\n" +
	"\arollout\x18\x04 \x01(\v2\x1c.google.protobuf.UInt32ValueR\arollout\"\x19\n" +
	"\x17SetRuleOverrideResponse\"\x8d\x01\n" +
	"\x16SetFlagOverrideRequest\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x12\x19\n" +
	"\bflag_key\x18\x02 \x01(\tR\aflagKey\x12;\n" +
	"\vkill_switch\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\n" +
	"killSwitch\"\x19\n" +
	"\x17SetFlagOverrideResponse\"\xab\x01\n" +
	"\x1aSetFlagRuleOverrideRequest\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x12\x19\n" +
	"\bflag_key\x18\x02 \x01(\tR\aflagKey\x12\x1d\n" +
	"\n" +
	"rule_index\x18\x03 \x01(\rR\truleIndex\x126\n" +
	"\arollout\x18\x04 \x01(\v2\x1c.google.protobuf.UInt32ValueR\arollout\"\x1d\n" +
	"\x1bSetFlagRuleOverrideResponse2\x9e\b\n" +
	"\x0eArbiterService\x12T\n" +
	"\rPublishBundle\x12 .arbiter.v1.PublishBundleRequest\x1a!.arbiter.v1.PublishBundleResponse\x12T\n" +
	"\rEvaluateRules\x12 .arbiter.v1.EvaluateRulesRequest\x1a!.arbiter.v1.EvaluateRulesResponse\x12N\n" +
	"\vResolveFlag\x12\x1e.arbiter.v1.ResolveFlagRequest\x1a\x1f.arbiter.v1.ResolveFlagResponse\x12Q\n" +
	"\fStartSession\x12\x1f.arbiter.v1.StartSessionRequest\x1a .arbiter.v1.StartSessionResponse\x12K\n" +
	"\n" +
	"RunSession\x12\x1d.arbiter.v1.RunSessionRequest\x1a\x1e.arbiter.v1.RunSessionResponse\x12N\n" +
	"\vAssertFacts\x12\x1e.arbiter.v1.AssertFactsRequest\x1a\x1f.arbiter.v1.AssertFactsResponse\x12Q\n" +
	"\fRetractFacts\x12\x1f.arbiter.v1.RetractFactsRequest\x1a .arbiter.v1.RetractFactsResponse\x12Z\n" +
	"\x0fGetSessionTrace\x12\".arbiter.v1.GetSessionTraceRequest\x1a#.arbiter.v1.GetSessionTraceResponse\x12Q\n" +
	"\fCloseSession\x12\x1f.arbiter.v1.CloseSessionRequest\x1a .arbiter.v1.CloseSessionResponse\x12Z\n" +
	"\x0fSetRuleOverride\x12\".arbiter.v1.SetRuleOverrideRequest\x1a#.arbiter.v1.SetRuleOverrideResponse\x12Z\n" +
	"\x0fSetFlagOverride\x12\".arbiter.v1.SetFlagOverrideRequest\x1a#.arbiter.v1.SetFlagOverrideResponse\x12f\n" +
	"\x13SetFlagRuleOverride\x12&.arbiter.v1.SetFlagRuleOverrideRequest\x1a'.arbiter.v1.SetFlagRuleOverrideResponseB7Z5github.com/odvcencio/arbiter/api/arbiter/v1;arbiterv1b\x06proto3"

var (
	file_arbiter_v1_service_proto_rawDescOnce sync.Once
	file_arbiter_v1_service_proto_rawDescData []byte
)

func file_arbiter_v1_service_proto_rawDescGZIP() []byte {
	file_arbiter_v1_service_proto_rawDescOnce.Do(func() {
		file_arbiter_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arbiter_v1_service_proto_rawDesc), len(file_arbiter_v1_service_proto_rawDesc)))
	})
	return file_arbiter_v1_service_proto_rawDescData
}

var file_arbiter_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_arbiter_v1_service_proto_goTypes = []any{
	(*PublishBundleRequest)(nil),        // 0: arbiter.v1.PublishBundleRequest
	(*PublishBundleResponse)(nil),       // 1: arbiter.v1.PublishBundleResponse
	(*TraceStep)(nil),                   // 2: arbiter.v1.TraceStep
	(*RuleMatch)(nil),                   // 3: arbiter.v1.RuleMatch
	(*EvaluateRulesRequest)(nil),        // 4: arbiter.v1.EvaluateRulesRequest
	(*EvaluateRulesResponse)(nil),       // 5: arbiter.v1.EvaluateRulesResponse
	(*ResolveFlagRequest)(nil),          // 6: arbiter.v1.ResolveFlagRequest
	(*ResolveFlagResponse)(nil),         // 7: arbiter.v1.ResolveFlagResponse
	(*ExpertFact)(nil),                  // 8: arbiter.v1.ExpertFact
	(*ExpertOutcome)(nil),               // 9: arbiter.v1.ExpertOutcome
	(*ExpertActivation)(nil),            // 10: arbiter.v1.ExpertActivation
	(*StartSessionRequest)(nil),         // 11: arbiter.v1.StartSessionRequest
	(*StartSessionResponse)(nil),        // 12: arbiter.v1.StartSessionResponse
	(*RunSessionRequest)(nil),           // 13: arbiter.v1.RunSessionRequest
	(*RunSessionResponse)(nil),          // 14: arbiter.v1.RunSessionResponse
	(*AssertFactsRequest)(nil),          // 15: arbiter.v1.AssertFactsRequest
	(*AssertFactsResponse)(nil),         // 16: arbiter.v1.AssertFactsResponse
	(*FactRef)(nil),                     // 17: arbiter.v1.FactRef
	(*RetractFactsRequest)(nil),         // 18: arbiter.v1.RetractFactsRequest
	(*RetractFactsResponse)(nil),        // 19: arbiter.v1.RetractFactsResponse
	(*GetSessionTraceRequest)(nil),      // 20: arbiter.v1.GetSessionTraceRequest
	(*GetSessionTraceResponse)(nil),     // 21: arbiter.v1.GetSessionTraceResponse
	(*CloseSessionRequest)(nil),         // 22: arbiter.v1.CloseSessionRequest
	(*CloseSessionResponse)(nil),        // 23: arbiter.v1.CloseSessionResponse
	(*SetRuleOverrideRequest)(nil),      // 24: arbiter.v1.SetRuleOverrideRequest
	(*SetRuleOverrideResponse)(nil),     // 25: arbiter.v1.SetRuleOverrideResponse
	(*SetFlagOverrideRequest)(nil),      // 26: arbiter.v1.SetFlagOverrideRequest
	(*SetFlagOverrideResponse)(nil),     // 27: arbiter.v1.SetFlagOverrideResponse
	(*SetFlagRuleOverrideRequest)(nil),  // 28: arbiter.v1.SetFlagRuleOverrideRequest
	(*SetFlagRuleOverrideResponse)(nil), // 29: arbiter.v1.SetFlagRuleOverrideResponse
	(*timestamppb.Timestamp)(nil),       // 30: google.protobuf.Timestamp
	(*structpb.Struct)(nil),             // 31: google.protobuf.Struct
	(*wrapperspb.BoolValue)(nil),        // 32: google.protobuf.BoolValue
	(*wrapperspb.UInt32Value)(nil),      // 33: google.protobuf.UInt32Value
}
var file_arbiter_v1_service_proto_depIdxs = []int32{
	30, // 0: arbiter.v1.PublishBundleResponse.published_at:type_name -> google.protobuf.Timestamp
	31, // 1: arbiter.v1.RuleMatch.params:type_name -> google.protobuf.Struct
	31, // 2: arbiter.v1.EvaluateRulesRequest.context:type_name -> google.protobuf.Struct
	3,  // 3: arbiter.v1.EvaluateRulesResponse.matched:type_name -> arbiter.v1.RuleMatch
	2,  // 4: arbiter.v1.EvaluateRulesResponse.trace:type_name -> arbiter.v1.TraceStep
	31, // 5: arbiter.v1.ResolveFlagRequest.context:type_name -> google.protobuf.Struct
	31, // 6: arbiter.v1.ResolveFlagResponse.values:type_name -> google.protobuf.Struct
	2,  // 7: arbiter.v1.ResolveFlagResponse.trace:type_name -> arbiter.v1.TraceStep
	31, // 8: arbiter.v1.ExpertFact.fields:type_name -> google.protobuf.Struct
	31, // 9: arbiter.v1.ExpertOutcome.params:type_name -> google.protobuf.Struct
	31, // 10: arbiter.v1.ExpertActivation.params:type_name -> google.protobuf.Struct
	31, // 11: arbiter.v1.StartSessionRequest.envelope:type_name -> google.protobuf.Struct
	8,  // 12: arbiter.v1.StartSessionRequest.facts:type_name -> arbiter.v1.ExpertFact
	9,  // 13: arbiter.v1.RunSessionResponse.outcomes:type_name -> arbiter.v1.ExpertOutcome
	8,  // 14: arbiter.v1.RunSessionResponse.facts:type_name -> arbiter.v1.ExpertFact
	10, // 15: arbiter.v1.RunSessionResponse.activations:type_name -> arbiter.v1.ExpertActivation
	8,  // 16: arbiter.v1.AssertFactsRequest.facts:type_name -> arbiter.v1.ExpertFact
	17, // 17: arbiter.v1.RetractFactsRequest.facts:type_name -> arbiter.v1.FactRef
	9,  // 18: arbiter.v1.GetSessionTraceResponse.outcomes:type_name -> arbiter.v1.ExpertOutcome
	8,  // 19: arbiter.v1.GetSessionTraceResponse.facts:type_name -> arbiter.v1.ExpertFact
	10, // 20: arbiter.v1.GetSessionTraceResponse.activations:type_name -> arbiter.v1.ExpertActivation
	32, // 21: arbiter.v1.SetRuleOverrideRequest.kill_switch:type_name -> google.protobuf.BoolValue
	33, // 22: arbiter.v1.SetRuleOverrideRequest.rollout:type_name -> google.protobuf.UInt32Value
	32, // 23: arbiter.v1.SetFlagOverrideRequest.kill_switch:type_name -> google.protobuf.BoolValue
	33, // 24: arbiter.v1.SetFlagRuleOverrideRequest.rollout:type_name -> google.protobuf.UInt32Value
	0,  // 25: arbiter.v1.ArbiterService.PublishBundle:input_type -> arbiter.v1.PublishBundleRequest
	4,  // 26: arbiter.v1.ArbiterService.EvaluateRules:input_type -> arbiter.v1.EvaluateRulesRequest
	6,  // 27: arbiter.v1.ArbiterService.ResolveFlag:input_type -> arbiter.v1.ResolveFlagRequest
	11, // 28: arbiter.v1.ArbiterService.StartSession:input_type -> arbiter.v1.StartSessionRequest
	13, // 29: arbiter.v1.ArbiterService.RunSession:input_type -> arbiter.v1.RunSessionRequest
	15, // 30: arbiter.v1.ArbiterService.AssertFacts:input_type -> arbiter.v1.AssertFactsRequest
	18, // 31: arbiter.v1.ArbiterService.RetractFacts:input_type -> arbiter.v1.RetractFactsRequest
	20, // 32: arbiter.v1.ArbiterService.GetSessionTrace:input_type -> arbiter.v1.GetSessionTraceRequest
	22, // 33: arbiter.v1.ArbiterService.CloseSession:input_type -> arbiter.v1.CloseSessionRequest
	24, // 34: arbiter.v1.ArbiterService.SetRuleOverride:input_type -> arbiter.v1.SetRuleOverrideRequest
	26, // 35: arbiter.v1.ArbiterService.SetFlagOverride:input_type -> arbiter.v1.SetFlagOverrideRequest
	28, // 36: arbiter.v1.ArbiterService.SetFlagRuleOverride:input_type -> arbiter.v1.SetFlagRuleOverrideRequest
	1,  // 37: arbiter.v1.ArbiterService.PublishBundle:output_type -> arbiter.v1.PublishBundleResponse
	5,  // 38: arbiter.v1.ArbiterService.EvaluateRules:output_type -> arbiter.v1.EvaluateRulesResponse
	7,  // 39: arbiter.v1.ArbiterService.ResolveFlag:output_type -> arbiter.v1.ResolveFlagResponse
	12, // 40: arbiter.v1.ArbiterService.StartSession:output_type -> arbiter.v1.StartSessionResponse
	14, // 41: arbiter.v1.ArbiterService.RunSession:output_type -> arbiter.v1.RunSessionResponse
	16, // 42: arbiter.v1.ArbiterService.AssertFacts:output_type -> arbiter.v1.AssertFactsResponse
	19, // 43: arbiter.v1.ArbiterService.RetractFacts:output_type -> arbiter.v1.RetractFactsResponse
	21, // 44: arbiter.v1.ArbiterService.GetSessionTrace:output_type -> arbiter.v1.GetSessionTraceResponse
	23, // 45: arbiter.v1.ArbiterService.CloseSession:output_type -> arbiter.v1.CloseSessionResponse
	25, // 46: arbiter.v1.ArbiterService.SetRuleOverride:output_type -> arbiter.v1.SetRuleOverrideResponse
	27, // 47: arbiter.v1.ArbiterService.SetFlagOverride:output_type -> arbiter.v1.SetFlagOverrideResponse
	29, // 48: arbiter.v1.ArbiterService.SetFlagRuleOverride:output_type -> arbiter.v1.SetFlagRuleOverrideResponse
	37, // [37:49] is the sub-list for method output_type
	25, // [25:37] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_arbiter_v1_service_proto_init() }
func file_arbiter_v1_service_proto_init() {
	if File_arbiter_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arbiter_v1_service_proto_rawDesc), len(file_arbiter_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arbiter_v1_service_proto_goTypes,
		DependencyIndexes: file_arbiter_v1_service_proto_depIdxs,
		MessageInfos:      file_arbiter_v1_service_proto_msgTypes,
	}.Build()
	File_arbiter_v1_service_proto = out.File
	file_arbiter_v1_service_proto_goTypes = nil
	file_arbiter_v1_service_proto_depIdxs = nil
}
